version: "3"
services:
  manager:
    container_name: manager
    image: skycoin/skywire:arm64v8
    ports:
      - 8000:8000
    command: skywire-manager -web-dir /usr/local/skycoin/net/skycoin-messenger/monitor/web/dist-manager
    volumes:
      - ./rpi/manager:/root/.skywire
  node1:
    container_name: node1
    image: skycoin/skywire:arm64v8
    environment:
      VIRTUAL_HOST: node.skywire.com
    volumes:
      - ./rpi/1:/root/.skywire
    depends_on:
      - manager
    command: skywire-node -connect-manager -manager-address manager:5998 -manager-web manager:8000 -address :5000 -web-port :6001 -discovery-address testnet.skywire.skycoin.com:5999-028ec969bdeb92a1991bb19c948645ac8150468a6919113061899051409de3f243
  node2:
    container_name: node2
    image: skycoin/skywire:arm64v8
    environment:
      VIRTUAL_HOST: node.skywire.com
    volumes:
      - ./rpi/2:/root/.skywire
    depends_on:
      - manager
    command: skywire-node -connect-manager -manager-address manager:5998 -manager-web manager:8000 -address :5000 -web-port :6001 -discovery-address testnet.skywire.skycoin.com:5999-028ec969bdeb92a1991bb19c948645ac8150468a6919113061899051409de3f243
  node3:
    container_name: node3
    image: skycoin/skywire:arm64v8
    environment:
      VIRTUAL_HOST: node.skywire.com
    volumes:
      - ./rpi/3:/root/.skywire
    depends_on:
      - manager
    command: skywire-node -connect-manager -manager-address manager:5998 -manager-web manager:8000 -address :5000 -web-port :6001 -discovery-address testnet.skywire.skycoin.com:5999-028ec969bdeb92a1991bb19c948645ac8150468a6919113061899051409de3f243
  node4:
    container_name: node4
    image: skycoin/skywire:arm64v8
    environment:
      VIRTUAL_HOST: node.skywire.com
    volumes:
      - ./rpi/4:/root/.skywire
    depends_on:
      - manager
    command: skywire-node -connect-manager -manager-address manager:5998 -manager-web manager:8000 -address :5000 -web-port :6001 -discovery-address testnet.skywire.skycoin.com:5999-028ec969bdeb92a1991bb19c948645ac8150468a6919113061899051409de3f243
  node5:
    container_name: node5
    image: skycoin/skywire:arm64v8
    environment:
      VIRTUAL_HOST: node.skywire.com
    volumes:
      - ./rpi/5:/root/.skywire
    depends_on:
      - manager
    command: skywire-node -connect-manager -manager-address manager:5998 -manager-web manager:8000 -address :5000 -web-port :6001 -discovery-address testnet.skywire.skycoin.com:5999-028ec969bdeb92a1991bb19c948645ac8150468a6919113061899051409de3f243
  node6:
    container_name: node6
    image: skycoin/skywire:arm64v8
    environment:
      VIRTUAL_HOST: node.skywire.com
    volumes:
      - ./rpi/6:/root/.skywire
    depends_on:
      - manager
    command: skywire-node -connect-manager -manager-address manager:5998 -manager-web manager:8000 -address :5000 -web-port :6001 -discovery-address testnet.skywire.skycoin.com:5999-028ec969bdeb92a1991bb19c948645ac8150468a6919113061899051409de3f243
  node7:
    container_name: node7
    image: skycoin/skywire:arm64v8
    environment:
      VIRTUAL_HOST: node.skywire.com
    volumes:
      - ./rpi/7:/root/.skywire
    depends_on:
      - manager
    command: skywire-node -connect-manager -manager-address manager:5998 -manager-web manager:8000 -address :5000 -web-port :6001 -discovery-address testnet.skywire.skycoin.com:5999-028ec969bdeb92a1991bb19c948645ac8150468a6919113061899051409de3f243
  nginx:
      container_name: nginx-proxy
      image: jwilder/nginx-proxy
      volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
      ports:
        - 5000:5000
        - 6001:6001
      volumes:
        - /var/run/docker.sock:/tmp/docker.sock:ro
      privileged: true