apiVersion: apps/v1
kind: Deployment
metadata:
  name: node
spec:
  replicas: 8
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - image: skycoin/skywire
        name: node
        ports:
          - name: address
            containerPort: 5000
          - name: web-port
            containerPort: 6001
        command: ["skywire-node", "-connect-manager", "-manager-address", "manager:5998", "-manager-web", "manager:8000", "-address", ":5000", "-web-port", ":6001", "-discovery-address", "discovery.skycoin.net:5999-034b1cd4ebad163e457fb805b3ba43779958bba49f2c5e1e8b062482904bacdb68"]
        volumeMounts:
        - name: skywire-data
          mountPath: /root/$HOSTNAME/.skywire
      volumes:
      - name: skywire-data
        persistentVolumeClaim:
          claimName: node-pv-claim
