kind: Service
apiVersion: v1
metadata:
  name: node 
spec:
  selector:
    app: node 
  ports:
  - name: address 
    port: 5000 
    targetPort: 5000 
  - name: web-port 
    port: 6001 
    targetPort: 6001 
